use angular signals
thanks to raknjarasoa on reddit

https://old.reddit.com/user/raknjarasoa

https://old.reddit.com/r/Angular2/comments/1hj9vse/please_help_i_am_trying_my_first_unit_tests_in/m34z4ng/

Not a direct response, but since you’re in v19, try to use signal input. Just run npx ng generate @angular/core:signal-input-migration

Re run your test after and tell us the results

kushal@kusfedora2024:~$ cd ~/src/myhtml/angularnineteen.github.io/; dura watch
/home/kushal/src/myhtml/angularnineteen.github.io is already being watched
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng test
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.
21 12 2024 09:42:43.855:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
21 12 2024 09:42:43.856:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
21 12 2024 09:42:43.861:INFO [launcher]: Starting browser Firefox
21 12 2024 09:42:44.798:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket AEK7h0CB5xabmyJIAAAB with id 47522576
Firefox 133.0 (Linux x86_64): Executed 7 of 7 SUCCESS (0.151 secs / 0.118 secs)
TOTAL: 7 SUCCESS
Done in 4.27s.

real	0m4.432s
user	0m5.658s
sys	0m1.426s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time npx ng generate @angular/core:signal-input-migration
✔ Which directory do you want to migrate? ./
✔ Do you want to migrate as much as possible, even if it may break your build? Yes
    Preparing analysis for: tsconfig.app.json..
    Preparing analysis for: tsconfig.spec.json..
    Scanning for inputs: tsconfig.app.json..
    Scanning for inputs: tsconfig.spec.json..

    Processing analysis data between targets..

    Migrating: tsconfig.app.json..
    Migrating: tsconfig.spec.json..
    Applying changes..

    Successfully migrated to signal inputs 🎉
      -> Migrated 8/8 inputs.
    You ran with best effort mode. Manually verify all code works as intended, and fix where necessary.
UPDATE src/app/stale-news-card/stale-news-card.component.ts (1851 bytes)
npm notice
npm notice New major version of npm available! 10.9.0 -> 11.0.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.0.0
npm notice To update run: npm install -g npm@11.0.0
npm notice

real	0m12.191s
user	0m4.031s
sys	0m0.435s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng build
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-ZE4SRBRA.js    | main          | 199.95 kB |                53.16 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 199.95 kB |                53.16 kB

Application bundle generation complete. [1.403 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.84s.

real	0m1.935s
user	0m2.747s
sys	0m0.320s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng build
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-ZE4SRBRA.js    | main          | 199.95 kB |                53.16 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 199.95 kB |                53.16 kB

Application bundle generation complete. [1.252 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.66s.

real	0m1.755s
user	0m2.599s
sys	0m0.290s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng test
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

28     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

21 12 2024 09:44:28.179:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
21 12 2024 09:44:28.180:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
21 12 2024 09:44:28.180:ERROR [karma-server]: Error: Found 1 load error
    at Server.<anonymous> (/home/kushal/src/myhtml/angularnineteen.github.io/node_modules/karma/lib/server.js:243:26)
    at Object.onceWrapper (node:events:638:28)
    at Server.emit (node:events:536:35)
    at emitListeningNT (node:net:1955:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

real	0m2.478s
user	0m3.637s
sys	0m0.610s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng test --watch
yarn run v1.22.22
$ ng test --watch
✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:30:5 - error TS2304: Cannot find name 'longFormText'.

30     longFormText = [];
       ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:40:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

40     component.title = '';
                 ~~~~~

21 12 2024 09:48:03.117:WARN [karma]: No captured browser, open http://localhost:9876/
21 12 2024 09:48:03.123:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
21 12 2024 09:48:03.123:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
21 12 2024 09:48:03.126:INFO [launcher]: Starting browser Firefox
21 12 2024 09:48:04.031:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket E6f7gqY_p02EO6ZXAAAB with id 93075648
21 12 2024 09:48:04.108:WARN [web-server]: 404: /_karma_webpack_/main.js
Firefox 133.0 (Linux x86_64): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
TOTAL: 0 SUCCESS
✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:31:31 - error TS2349: This expression is not callable.
  Type 'StaleNewsCardComponent' has no call signatures.

31     let component1 = fixture1.componentInstance(
                                 ~~~~~~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:34:5 - error TS2304: Cannot find name 'longFormText'.

34     longFormText = [];
       ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:44:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

44     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:30:5 - error TS2304: Cannot find name 'longFormText'.

30     longFormText = [];
       ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:40:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

40     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:30:5 - error TS2304: Cannot find name 'longFormText'.

30     longFormText = [];
       ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:40:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

40     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

28     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:15 - error TS2551: Property 'updatelongFormText' does not exist on type 'StaleNewsCardComponent'. Did you mean 'longFormText'?

28     component.updatelongFormText = [];
                 ~~~~~~~~~~~~~~~~~~

  src/app/stale-news-card/stale-news-card.component.ts:64:12
    64   readonly longFormText = input<string[]>([]); // Change to an array of strings
                  ~~~~~~~~~~~~
    'longFormText' is declared here.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

28     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

./src/app/stale-news-card/stale-news-card.component.spec.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
SyntaxError: /home/kushal/src/myhtml/angularnineteen.github.io/src/app/stale-news-card/stale-news-card.component.spec.ts: Invalid left-hand side in assignment expression. (23:8)

  21 |     });
  22 |     it('should handle empty long form text', async () => {
> 23 |         component.longFormText.update() = [];
     |         ^
  24 |         fixture.detectChanges();
  25 |         await fixture.whenStable();
  26 |         const compiled = fixture.nativeElement;

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:5 - error TS2364: The left-hand side of an assignment expression must be a variable or a property access.

28     component.longFormText.update() = [];
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:28 - error TS2339: Property 'update' does not exist on type 'InputSignal<string[]>'.

28     component.longFormText.update() = [];
                              ~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:28 - error TS2339: Property 'update' does not exist on type 'InputSignal<string[]>'.

28     component.longFormText.update([]);
                              ~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:28 - error TS2339: Property 'set' does not exist on type 'InputSignal<string[]>'.

28     component.longFormText.set([]);
                              ~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

28     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:38:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

38     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:15 - error TS2339: Property 'set' does not exist on type 'StaleNewsCardComponent'.

28     component.set
                 ~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:29:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

29     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:39:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

39     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:26 - error TS2339: Property 'Set' does not exist on type 'ComponentRef<StaleNewsCardComponent>'.

28     fixture.componentRef.Set
                            ~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:29:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

29     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:39:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

39     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:26 - error TS2554: Expected 2 arguments, but got 0.

28     fixture.componentRef.setInput(
                            ~~~~~~~~

  node_modules/@angular/core/index.d.ts:2168:23
    2168     abstract setInput(name: string, value: unknown): void;
                               ~~~~~~~~~~~~
    An argument for 'name' was not provided.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:31:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

31     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:41:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

41     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

./src/app/stale-news-card/stale-news-card.component.spec.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):
SyntaxError: /home/kushal/src/myhtml/angularnineteen.github.io/src/app/stale-news-card/stale-news-card.component.spec.ts: Invalid left-hand side in assignment expression. (23:38)

  21 |     });
  22 |     it('should handle empty long form text', async () => {
> 23 |         fixture.componentRef.setInput('longFormText' = '');
     |                                       ^
  24 |         component.longFormText = [];
  25 |         fixture.detectChanges();
  26 |         await fixture.whenStable();

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:28:26 - error TS2554: Expected 2 arguments, but got 1.

28     fixture.componentRef.setInput(
                            ~~~~~~~~

  node_modules/@angular/core/index.d.ts:2168:37
    2168     abstract setInput(name: string, value: unknown): void;
                                             ~~~~~~~~~~~~~~
    An argument for 'value' was not provided.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:29:7 - error TS2364: The left-hand side of an assignment expression must be a variable or a property access.

29       'longFormText' = ''
         ~~~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:31:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

31     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:41:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

41     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:31:15 - error TS2540: Cannot assign to 'longFormText' because it is a read-only property.

31     component.longFormText = [];
                 ~~~~~~~~~~~~

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:41:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

41     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.

Error: src/app/stale-news-card/stale-news-card.component.spec.ts:40:15 - error TS2540: Cannot assign to 'title' because it is a read-only property.

40     component.title = '';
                 ~~~~~

✔ Browser application bundle generation complete.
Firefox 133.0 (Linux x86_64): Executed 7 of 7 SUCCESS (0.116 secs / 0.109 secs)
TOTAL: 7 SUCCESS
✔ Browser application bundle generation complete.
Firefox 133.0 (Linux x86_64) StaleNewsCardComponent should handle Lorem Ipsum title FAILED
	Expected 'Lorem ipsum dolor' to be 'Lorem Ipsum'.
	<Jasmine>
	1379/</<@main.js:470:31
	asyncGeneratorStep@vendor.js:105118:17
	_next@vendor.js:105132:27
Firefox 133.0 (Linux x86_64): Executed 8 of 8 (1 FAILED) (0.093 secs / 0.083 secs)
TOTAL: 1 FAILED, 7 SUCCESS
✔ Browser application bundle generation complete.
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.076 secs / 0.071 secs)
TOTAL: 8 SUCCESS
^C
real	17m56.836s
user	0m0.201s
sys	0m0.076s

Firefox 133.0 (Linux x86_64) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.076 secs / 0.071 secs)
Firefox 133.0 (Linux x86_64) ERROR
  Disconnected Client disconnected from CONNECTED state (transport close)

kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng build
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-ZE4SRBRA.js    | main          | 199.95 kB |                53.16 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 199.95 kB |                53.16 kB

Application bundle generation complete. [1.220 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.63s.

real	0m1.725s
user	0m2.546s
sys	0m0.306s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng test
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.
21 12 2024 10:06:11.833:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
21 12 2024 10:06:11.833:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
21 12 2024 10:06:11.836:INFO [launcher]: Starting browser Firefox
21 12 2024 10:06:12.760:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket UFn9FbzD8osRsh3zAAAB with id 79697962
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.121 secs / 0.118 secs)
TOTAL: 8 SUCCESS
Done in 3.44s.

real	0m3.539s
user	0m5.156s
sys	0m1.195s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$