clean up
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ time ng test
✔ Browser application bundle generation complete.
30 12 2024 18:41:14.507:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
30 12 2024 18:41:14.507:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
30 12 2024 18:41:14.510:INFO [launcher]: Starting browser Firefox
30 12 2024 18:41:15.475:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket 161upTVF1cQI_iRhAAAB with id 94717642
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.133 secs / 0.12 secs)
TOTAL: 8 SUCCESS

real	0m3.893s
user	0m5.566s
sys	0m1.450s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng build; time yarn run ng test
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-SNZVYGR6.js    | main          | 206.61 kB |                55.02 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 206.61 kB |                55.02 kB

Application bundle generation complete. [1.314 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.74s.

real	0m1.839s
user	0m2.728s
sys	0m0.333s
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.
30 12 2024 18:42:50.594:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
30 12 2024 18:42:50.595:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
30 12 2024 18:42:50.616:INFO [launcher]: Starting browser Firefox
30 12 2024 18:42:51.544:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket txqtDiwshbZkxdESAAAB with id 41218420
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.121 secs / 0.114 secs)
TOTAL: 8 SUCCESS
Done in 3.43s.

real	0m3.534s
user	0m4.895s
sys	0m1.205s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng build; time yarn run ng test
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-SNZVYGR6.js    | main          | 206.61 kB |                55.02 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 206.61 kB |                55.02 kB

Application bundle generation complete. [1.268 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.66s.

real	0m1.760s
user	0m2.660s
sys	0m0.287s
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.
30 12 2024 18:45:09.885:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
30 12 2024 18:45:09.886:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
30 12 2024 18:45:09.895:INFO [launcher]: Starting browser Firefox
30 12 2024 18:45:10.856:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket eGEC30iCalBU_GphAAAB with id 1890699
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.115 secs / 0.11 secs)
TOTAL: 8 SUCCESS
Done in 3.63s.

real	0m3.731s
user	0m5.414s
sys	0m1.217s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time bash update.sh
Mon Dec 30 06:46:14 PM EST 2024
error: cannot pull with rebase: You have unstaged changes.
error: additionally, your index contains uncommitted changes.
error: Please commit or stash them.
0.40.1
Installing latest LTS version.
v22.12.0 is already installed.
Now using node v22.12.0 (npm v10.9.0)
v22.12.0
10.9.0

changed 1 package in 531ms
Mon Dec 30 06:46:16 PM EST 2024
Mon Dec 30 06:46:16 PM EST 2024
yarn install v1.22.22
info No lockfile found.
[1/4] Resolving packages...
warning karma-coverage-istanbul-reporter > istanbul-lib-source-maps > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
warning karma-coverage-istanbul-reporter > istanbul-lib-source-maps > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning karma-coverage-istanbul-reporter > istanbul-lib-source-maps > rimraf > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
warning karma > glob@7.2.3: Glob versions prior to v9 are no longer supported
warning karma > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning karma > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@angular-devkit/build-angular > @vitejs/plugin-basic-ssl@1.1.0" has unmet peer dependency "vite@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@angular-devkit/build-angular > @angular/build > @inquirer/confirm@5.0.2" has unmet peer dependency "@types/node@>=18".
warning "@angular-devkit/build-angular > @angular/build > @inquirer/confirm > @inquirer/type@3.0.2" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts@7.1.0" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/confirm@5.1.1" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/input@4.1.1" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/editor@4.2.1" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/expand@4.0.4" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/search@3.0.4" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/checkbox@4.0.4" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/number@3.0.4" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/rawlist@4.0.4" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/select@4.0.4" has unmet peer dependency "@types/node@>=18".
warning "@angular/cli > @inquirer/prompts > @inquirer/password@4.0.4" has unmet peer dependency "@types/node@>=18".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 8.36s.

real    0m8.484s
user    0m3.444s
sys	0m1.027s
Mon Dec 30 06:46:24 PM EST 2024
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   public/notes/2024/12/31/build.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   public/notes/2024/12/31/build.txt

[master 0bb3851] add all files
 1 file changed, 77 insertions(+)
 create mode 100644 public/notes/2024/12/31/build.txt
From github.com:angularnineteen/angularnineteen.github.io
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 29, done.
Counting objects: 100% (29/29), done.
Delta compression using up to 16 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (17/17), 64.80 KiB | 16.20 MiB/s, done.
Total 17 (delta 9), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (9/9), completed with 8 local objects.
To github.com:angularnineteen/angularnineteen.github.io.git
   6b984a2..0bb3851  master -> master
yarn install v1.22.22
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.18s.
yarn run v1.22.22
$ ng update
Using package manager: yarn
Collecting installed dependencies...
Found 25 dependencies.
    We analyzed your package.json and everything seems to be in order. Good work!
Done in 0.85s.
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-SNZVYGR6.js    | main          | 206.61 kB |                55.02 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 206.61 kB |                55.02 kB

Application bundle generation complete. [1.283 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.69s.
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	docs/notes/2024/12/31/build.txt

nothing added to commit but untracked files present (use "git add" to track)
[master aa53f85] add all files
 1 file changed, 77 insertions(+)
 create mode 100644 docs/notes/2024/12/31/build.txt
From github.com:angularnineteen/angularnineteen.github.io
 * branch            master     -> FETCH_HEAD
Current branch master is up to date.
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 16 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 1.38 KiB | 1.38 MiB/s, done.
Total 8 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:angularnineteen/angularnineteen.github.io.git
   0bb3851..aa53f85  master -> master
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.
30 12 2024 18:46:33.739:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
30 12 2024 18:46:33.740:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
30 12 2024 18:46:33.743:INFO [launcher]: Starting browser Firefox
30 12 2024 18:46:34.692:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket F_JP9_QUohoAAd8HAAAB with id 915106
Firefox 133.0 (Linux x86_64): Executed 8 of 8 SUCCESS (0.097 secs / 0.122 secs)
TOTAL: 8 SUCCESS
Done in 3.59s.
yarn run v1.22.22
$ ng update @angular/core @angular/cli
Using package manager: yarn
Collecting installed dependencies...
Found 25 dependencies.
Fetching dependency metadata from registry...
Package '@angular/core' is already up to date.
Package '@angular/cli' is already up to date.
Done in 0.74s.
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
From github.com:angularnineteen/angularnineteen.github.io
 * branch            master     -> FETCH_HEAD
Already up to date.
Everything up-to-date
Latest version:     1.0.30001690
Installed version:  1.0.30001690
caniuse-lite is up to date
caniuse-lite has been successfully updated

No target browser changes
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
From github.com:angularnineteen/angularnineteen.github.io
 * branch            master     -> FETCH_HEAD
Already up to date.
Enumerating objects: 74, done.
Counting objects: 100% (69/69), done.
Delta compression using up to 16 threads
Compressing objects: 100% (52/52), done.
Writing objects: 100% (54/54), 5.42 KiB | 1.35 MiB/s, done.
Total 54 (delta 33), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (33/33), completed with 6 local objects.
To github.com:angularnineteen/angularnineteen.github.io.git
 * [new branch]      dura/61cb157fe82b62f9934f0028478faf764c27d846 -> dura/61cb157fe82b62f9934f0028478faf764c27d846
 * [new branch]      dura/e950799d67dcdc7b9c6b60f15ac2a467bacb2f7c -> dura/e950799d67dcdc7b9c6b60f15ac2a467bacb2f7c
* remote origin
  Fetch URL: git@github.com:angularnineteen/angularnineteen.github.io.git
  Push  URL: git@github.com:angularnineteen/angularnineteen.github.io.git
  HEAD branch: master
  Remote branches:
    dura/013a27a7c519e1f81fcbf38ebf25539dd5872740 tracked
    dura/167f43ab869b82f599d83d7a0a127f3e0b32c4b7 tracked
    dura/18a1fa6f138773f0629923a89e08880e979aaefd tracked
    dura/1e86fb3d344fb5c5ab336156646fd56ab73ce602 tracked
    dura/289ec2aea0b2758cf55694cfc4161fcba9460cf2 tracked
    dura/2d37193ecef229f4d0786faf5095a94a5d1b9ade tracked
    dura/2ddc38e1e97e80bd95ccf2b5ac9e04f6281a766a tracked
    dura/2f2ae662fc3ec04a8e38f92a33f7ac80ad446a46 tracked
    dura/305633b89af5a13d7e1ce35ed309197377641002 tracked
    dura/393bee3c58c1feaabc635781843d65d88b3f624e tracked
    dura/3ede3b72ec3e3ee2c09a9db94b8fec23e7e5c83b tracked
    dura/4d3a736be5bd701384bf87e28ba14d6311d2a7dc tracked
    dura/530777a2aa20c9e16aa97ae73ce29a9c63c8de94 tracked
    dura/566c4245c3993ad2ffe96e5ccf5fb198e459ed15 tracked
    dura/61cb157fe82b62f9934f0028478faf764c27d846 tracked
    dura/6257d5034f547dc7d9c213b6d9c78c60cec0db33 tracked
    dura/651f8a1d9fdce892918c9056a0764adb55339d66 tracked
    dura/726da9d9c75f98901124601ebfd2da03030b6dba tracked
    dura/7e76ee4c3eb8631a91e6ecf4ea6813bedd00c889 tracked
    dura/874eb9492ff078645de7600862878165773ca7c1 tracked
    dura/94dec830c4d8eba631efe85fdd9e078fd009fe24 tracked
    dura/ab097018dfc36950bee2ca2bb42d8b75536f9e30 tracked
    dura/b1f587444e4d48c232f4918c520b328231d009f3 tracked
    dura/b3f11fcf18e2ee2c8141d5dafbd03c54729810b1 tracked
    dura/bb2052670805c59d84715d90c29ba9bb4babb2a3 tracked
    dura/bdca41dbd9072519a04b8763e1873f3ae0c4e921 tracked
    dura/d235f88698d5674b55487577b92835e52f8aaf09 tracked
    dura/e53120b9b328bb40701ab5df4483fa289f012316 tracked
    dura/e7d3f0dd86f8740495226d4f48744188d298d830 tracked
    dura/e950799d67dcdc7b9c6b60f15ac2a467bacb2f7c tracked
    dura/ed1c34f9d96e6969290dd5d69c78e907003360f1 tracked
    dura/f11c53fa6b38d6a4bdcc104ffb20b2a93442a4fd tracked
    dura/f490d6a671cf2662798698aa56f36844e8623253 tracked
    dura/fe0fc2ae80b9ab7400d05cac84b443430e5b65be tracked
    master                                        tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local refs configured for 'git push':
    dura/013a27a7c519e1f81fcbf38ebf25539dd5872740 pushes to dura/013a27a7c519e1f81fcbf38ebf25539dd5872740 (up to date)
    dura/167f43ab869b82f599d83d7a0a127f3e0b32c4b7 pushes to dura/167f43ab869b82f599d83d7a0a127f3e0b32c4b7 (up to date)
    dura/18a1fa6f138773f0629923a89e08880e979aaefd pushes to dura/18a1fa6f138773f0629923a89e08880e979aaefd (up to date)
    dura/1e86fb3d344fb5c5ab336156646fd56ab73ce602 pushes to dura/1e86fb3d344fb5c5ab336156646fd56ab73ce602 (up to date)
    dura/289ec2aea0b2758cf55694cfc4161fcba9460cf2 pushes to dura/289ec2aea0b2758cf55694cfc4161fcba9460cf2 (up to date)
    dura/2d37193ecef229f4d0786faf5095a94a5d1b9ade pushes to dura/2d37193ecef229f4d0786faf5095a94a5d1b9ade (up to date)
    dura/2ddc38e1e97e80bd95ccf2b5ac9e04f6281a766a pushes to dura/2ddc38e1e97e80bd95ccf2b5ac9e04f6281a766a (up to date)
    dura/2f2ae662fc3ec04a8e38f92a33f7ac80ad446a46 pushes to dura/2f2ae662fc3ec04a8e38f92a33f7ac80ad446a46 (up to date)
    dura/305633b89af5a13d7e1ce35ed309197377641002 pushes to dura/305633b89af5a13d7e1ce35ed309197377641002 (up to date)
    dura/3ede3b72ec3e3ee2c09a9db94b8fec23e7e5c83b pushes to dura/3ede3b72ec3e3ee2c09a9db94b8fec23e7e5c83b (up to date)
    dura/4d3a736be5bd701384bf87e28ba14d6311d2a7dc pushes to dura/4d3a736be5bd701384bf87e28ba14d6311d2a7dc (up to date)
    dura/530777a2aa20c9e16aa97ae73ce29a9c63c8de94 pushes to dura/530777a2aa20c9e16aa97ae73ce29a9c63c8de94 (up to date)
    dura/566c4245c3993ad2ffe96e5ccf5fb198e459ed15 pushes to dura/566c4245c3993ad2ffe96e5ccf5fb198e459ed15 (up to date)
    dura/61cb157fe82b62f9934f0028478faf764c27d846 pushes to dura/61cb157fe82b62f9934f0028478faf764c27d846 (up to date)
    dura/6257d5034f547dc7d9c213b6d9c78c60cec0db33 pushes to dura/6257d5034f547dc7d9c213b6d9c78c60cec0db33 (up to date)
    dura/651f8a1d9fdce892918c9056a0764adb55339d66 pushes to dura/651f8a1d9fdce892918c9056a0764adb55339d66 (up to date)
    dura/726da9d9c75f98901124601ebfd2da03030b6dba pushes to dura/726da9d9c75f98901124601ebfd2da03030b6dba (up to date)
    dura/7e76ee4c3eb8631a91e6ecf4ea6813bedd00c889 pushes to dura/7e76ee4c3eb8631a91e6ecf4ea6813bedd00c889 (up to date)
    dura/ab097018dfc36950bee2ca2bb42d8b75536f9e30 pushes to dura/ab097018dfc36950bee2ca2bb42d8b75536f9e30 (up to date)
    dura/b3f11fcf18e2ee2c8141d5dafbd03c54729810b1 pushes to dura/b3f11fcf18e2ee2c8141d5dafbd03c54729810b1 (up to date)
    dura/bdca41dbd9072519a04b8763e1873f3ae0c4e921 pushes to dura/bdca41dbd9072519a04b8763e1873f3ae0c4e921 (up to date)
    dura/d235f88698d5674b55487577b92835e52f8aaf09 pushes to dura/d235f88698d5674b55487577b92835e52f8aaf09 (up to date)
    dura/e53120b9b328bb40701ab5df4483fa289f012316 pushes to dura/e53120b9b328bb40701ab5df4483fa289f012316 (up to date)
    dura/e7d3f0dd86f8740495226d4f48744188d298d830 pushes to dura/e7d3f0dd86f8740495226d4f48744188d298d830 (up to date)
    dura/e950799d67dcdc7b9c6b60f15ac2a467bacb2f7c pushes to dura/e950799d67dcdc7b9c6b60f15ac2a467bacb2f7c (up to date)
    dura/ed1c34f9d96e6969290dd5d69c78e907003360f1 pushes to dura/ed1c34f9d96e6969290dd5d69c78e907003360f1 (up to date)
    dura/f11c53fa6b38d6a4bdcc104ffb20b2a93442a4fd pushes to dura/f11c53fa6b38d6a4bdcc104ffb20b2a93442a4fd (up to date)
    dura/f490d6a671cf2662798698aa56f36844e8623253 pushes to dura/f490d6a671cf2662798698aa56f36844e8623253 (up to date)
    dura/fe0fc2ae80b9ab7400d05cac84b443430e5b65be pushes to dura/fe0fc2ae80b9ab7400d05cac84b443430e5b65be (up to date)
    master                                        pushes to master                                        (up to date)
Mon Dec 30 06:46:40 PM EST 2024

real	0m26.116s
user	0m15.401s
sys	0m4.086s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$ cd ~/src/myhtml/angularnineteen.github.io/; time yarn run ng build; time yarn run ng test
yarn run v1.22.22
$ ng build
Initial chunk files | Names         |  Raw size | Estimated transfer size
main-PP7TTRLO.js    | main          | 207.32 kB |                55.10 kB
styles-5INURTSO.css | styles        |   0 bytes |                 0 bytes

                    | Initial total | 207.32 kB |                55.10 kB

Application bundle generation complete. [1.338 seconds]

Output location: /home/kushal/src/myhtml/angularnineteen.github.io/docs

Done in 1.75s.

real	0m1.853s
user	0m2.760s
sys	0m0.330s
yarn run v1.22.22
$ ng test
✔ Browser application bundle generation complete.
30 12 2024 18:55:05.948:INFO [karma-server]: Karma v6.4.4 server started at http://localhost:9876/
30 12 2024 18:55:05.949:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
30 12 2024 18:55:05.952:INFO [launcher]: Starting browser Firefox
30 12 2024 18:55:06.883:INFO [Firefox 133.0 (Linux x86_64)]: Connected on socket fm5zMj1k4Z1KAjc_AAAB with id 15404789
Firefox 133.0 (Linux x86_64) StaleNewsCardComponent should handle empty title FAILED
	Expected ' - 0' to be ''.
	<Jasmine>
	1379/</<@main.js:460:31
	asyncGeneratorStep@vendor.js:105145:17
	_next@vendor.js:105159:27
Firefox 133.0 (Linux x86_64) StaleNewsCardComponent should handle Lorem Ipsum title FAILED
	Expected 'Lorem Ipsum - 0' to be 'Lorem Ipsum'.
	<Jasmine>
	1379/</<@main.js:470:31
	asyncGeneratorStep@vendor.js:105145:17
	_next@vendor.js:105159:27
Firefox 133.0 (Linux x86_64): Executed 8 of 8 (2 FAILED) (0.126 secs / 0.114 secs)
TOTAL: 2 FAILED, 6 SUCCESS
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

real	0m3.875s
user	0m5.321s
sys	0m1.357s
kushal@kusfedora2024:~/src/myhtml/angularnineteen.github.io$